--Amanat in query
                

   WITH LOV_DATE AS (
    SELECT
        PO.PO_ID,
        MAX(SR.SR_ID) SR_ID,
        MAX(CASE WHEN SR.REG_TYPE = 'WAREHOUSE' AND SR.SR_ID = POD.WAREHOUSE_ID THEN SR.REG_NAME END) AS WAREHOUSE_NAME,
        MAX(CASE WHEN SR.REG_TYPE = 'CUSTOMER REGISTRATION' AND SR.SR_ID = PO.CUSTOMER_ID THEN SR.REG_NAME END) AS CUSTOMER_NAME,
        TO_CHAR(PO.CREATED_ON, 'DD-MON-YYYY') AS CREATED_ON
    FROM
        AB_PO_PURCHASE_ORDER PO
        JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.PO_ID = PO.PO_ID
        JOIN AB_SETUP_REGISTRATION SR ON SR.SR_ID IN (POD.WAREHOUSE_ID, PO.CUSTOMER_ID)
    GROUP BY
        PO.PO_ID,
        PO.CREATED_ON
)
SELECT

   LD.CUSTOMER_NAME,
    NVL(SUM(POD.CHANGE_BAGS),0) AS AMANAT_In_BAGS
    
    
FROM
    AB_ITEMS_MASTER ITM
    JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.ITEM_ID = ITM.ITEM_ID
    JOIN AB_PO_PURCHASE_ORDER PO ON PO.PO_ID = POD.PO_ID
    JOIN LOV_DATE LD ON LD.PO_ID = POD.PO_ID
WHERE
    PO.PO_TYPE = 'AMANAT'
     AND NVL(LD.SR_ID,0) = NVL(:P273_CUSTOMER_ID,0)
  
    AND POD.ORG_ID = :GV_ORG_ID
GROUP BY
   
    LD.CUSTOMER_NAME
===============================================================================
--Amanat out query 

                

   WITH LOV_DATE AS (
    SELECT
        PO.PO_ID,
        MAX(SR.SR_ID) SR_ID,
        MAX(CASE WHEN SR.REG_TYPE = 'WAREHOUSE' AND SR.SR_ID = POD.WAREHOUSE_ID THEN SR.REG_NAME END) AS WAREHOUSE_NAME,
        MAX(CASE WHEN SR.REG_TYPE = 'CUSTOMER REGISTRATION' AND SR.SR_ID = PO.CUSTOMER_ID THEN SR.REG_NAME END) AS CUSTOMER_NAME,
        TO_CHAR(PO.CREATED_ON, 'DD-MON-YYYY') AS CREATED_ON
    FROM
        AB_PO_PURCHASE_ORDER PO
        JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.PO_ID = PO.PO_ID
        JOIN AB_SETUP_REGISTRATION SR ON SR.SR_ID IN (POD.WAREHOUSE_ID, PO.CUSTOMER_ID)
    GROUP BY
        PO.PO_ID,
        PO.CREATED_ON
)
SELECT
   
   LD.CUSTOMER_NAME,
    NVL(SUM(POD.CHANGE_BAGS),0) AS AMANAT_Out_BAGS
    
    
FROM
    AB_ITEMS_MASTER ITM
    JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.ITEM_ID = ITM.ITEM_ID
    JOIN AB_PO_PURCHASE_ORDER PO ON PO.PO_ID = POD.PO_ID
    JOIN LOV_DATE LD ON LD.PO_ID = POD.PO_ID
WHERE
    PO.PO_TYPE = 'AMANAT OUT'
  AND NVL(LD.SR_ID,0) = :P273_CUSTOMER_ID
  
    AND POD.ORG_ID = :GV_ORG_ID
GROUP BY
  
    LD.CUSTOMER_NAME
--========================================================================
--Amanat in - Amanat out
WITH LOV_DATE AS (
    SELECT
        PO.PO_ID,
        MAX(SR.SR_ID) SR_ID,
        MAX(CASE WHEN SR.REG_TYPE = 'WAREHOUSE' AND SR.SR_ID = POD.WAREHOUSE_ID THEN SR.REG_NAME END) AS WAREHOUSE_NAME,
        MAX(CASE WHEN SR.REG_TYPE = 'CUSTOMER REGISTRATION' AND SR.SR_ID = PO.CUSTOMER_ID THEN SR.REG_NAME END) AS CUSTOMER_NAME,
        TO_CHAR(PO.CREATED_ON, 'DD-MON-YYYY') AS CREATED_ON
    FROM
        AB_PO_PURCHASE_ORDER PO
        JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.PO_ID = PO.PO_ID
        JOIN AB_SETUP_REGISTRATION SR ON SR.SR_ID IN (POD.WAREHOUSE_ID, PO.CUSTOMER_ID)
    GROUP BY
        PO.PO_ID,
        PO.CREATED_ON
),
AMANAT_BAGS_IN AS (
    SELECT
        LD.SR_ID,
        LD.CUSTOMER_NAME,
        NVL(SUM(POD.CHANGE_BAGS), 0) AS AMANAT_BAGS
    FROM
        AB_ITEMS_MASTER ITM
        JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.ITEM_ID = ITM.ITEM_ID
        JOIN AB_PO_PURCHASE_ORDER PO ON PO.PO_ID = POD.PO_ID
        JOIN LOV_DATE LD ON LD.PO_ID = POD.PO_ID
    WHERE
        PO.PO_TYPE = 'AMANAT'
        AND NVL(LD.SR_ID, 0) = NVL(:P273_CUSTOMER_ID, 0)
        AND POD.ORG_ID = :GV_ORG_ID
    GROUP BY
        LD.SR_ID,
        LD.CUSTOMER_NAME
),
AMANAT_BAGS_OUT AS (
    SELECT
      
        LD.SR_ID,
        LD.CUSTOMER_NAME,
        NVL(SUM(POD.CHANGE_BAGS), 0) AS AMANAT_BAGS
    FROM
        AB_ITEMS_MASTER ITM
        JOIN AB_PO_PURCHASE_ORDER_DET POD ON POD.ITEM_ID = ITM.ITEM_ID
        JOIN AB_PO_PURCHASE_ORDER PO ON PO.PO_ID = POD.PO_ID
        JOIN LOV_DATE LD ON LD.PO_ID = POD.PO_ID
    WHERE
        PO.PO_TYPE = 'AMANAT OUT'
        AND NVL(LD.SR_ID, 0) = :P273_CUSTOMER_ID
        AND POD.ORG_ID = :GV_ORG_ID
    GROUP BY
        LD.SR_ID,
        LD.CUSTOMER_NAME
)
SELECT
    
    IN_DATA.CUSTOMER_NAME,
    (IN_DATA.AMANAT_BAGS - NVL(OUT_DATA.AMANAT_BAGS, 0)) AS NET_AMANAT_BAGS
FROM
    AMANAT_BAGS_IN IN_DATA
LEFT JOIN
    AMANAT_BAGS_OUT OUT_DATA
ON
    IN_DATA.SR_ID = OUT_DATA.SR_ID
    AND IN_DATA.CUSTOMER_NAME = OUT_DATA.CUSTOMER_NAME
  

   
  
