WITH OPENING_BALANCE AS(
    SELECT
        ACCOUNT_ID,
        TR_DATE AS TRANSCATION_DATE,
        TR_AMOUNT OPENING_BALANCE,
        DEPOSIT_AMOUNT SECURITY_DEPOSIT
    FROM
         AB_FIN_TRANSACTION TR
    WHERE 
           TR_TYPE = 625   
       AND ORG_ID=:GV_ORG_ID
       AND STATUS='Y'
),ACCOUNT_NOO AS (
    SELECT         
        DISTINCT     
        ASM.ACCOUNT_NUMBER ACCOUNT_NO,
        ASM.SR_ID  ACCOUNT_ID
    FROM 
             AB_SETUP_REGISTRATION ASM
        JOIN AB_SETUP_REGISTRATION AST ON AST.SR_ID=ASM.BANK_ID AND AST.REG_TYPE='BANK'
    LEFT JOIN AB_SETUP_REGISTRATION ASRC ON ASRC.SR_ID=ASM.COMPANY_ID AND ASRC.REG_TYPE='COMPANY'
    LEFT JOIN OPENING_BALANCE OB ON OB.ACCOUNT_ID=ASM.SR_ID
    WHERE 
           ASM.REG_TYPE IN ('BANK LOV','624')
      AND ASM.REG_STATUS = 'Y'
       AND ASM.ORG_ID = :GV_ORG_ID
     )
      
    SELECT
       RBS.ID,
       RBS.BANK_NAME,
       RBS.BANK_BRANCH,
       RBS.ACCOUNT_NO ACCOUNT_ID,
       AC.ACCOUNT_NO ,
       RBS.COMPANY_NAME,
       RBS.FROM_DATE,
       RBS.TO_DATES,
       TO_CHAR(RBS.CREATED_ON,'DD-MON-YYYY') || ' - '|| RBS.CREATED_BY AS ADD_BY,
       RBS.CREATED_BY,
       RBS.UPDATED_ON,
       RBS.UPDATED_BY,
       RBS.ORG_ID,
       RBS.STATUS,
       RBS.SUBJECT,
       RBS.AUTHORIZE_NAME,
       RBS.SON_NAME,
       RBS.CNIC,
       REQUEST_DATE,
       SUBJECT_DETAIL,
       'Report Show' as PRINT
  from REQUEST_BANK_STATEMENTS RBS 
  LEFT JOIN ACCOUNT_NOO AC ON AC.ACCOUNT_ID = RBS.ACCOUNT_NO
  order by RBS.id desc
